# Generated by Django 5.2.1 on 2025-05-29 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, verbose_name='닉네임')),
                ('mascot', models.CharField(blank=True, max_length=50, verbose_name='마스코트')),
                ('theme', models.CharField(blank=True, max_length=50, verbose_name='테마')),
                ('point', models.IntegerField(default=0, verbose_name='포인트')),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='계정')),
            ],
        ),
    ]
