# Generated by Django 5.2.1 on 2025-05-29 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('display_name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('bg_color', models.CharField(blank=True, max_length=15)),
                ('main_color', models.CharField(blank=True, max_length=15)),
                ('mascot_image', models.URLField(blank=True)),
                ('preview_image', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mascot',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='point',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='theme',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mascot_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='selected_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.theme'),
        ),
    ]
