# Generated by Django 5.2.1 on 2025-05-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_theme_remove_userprofile_join_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
