# Generated by Django 5.2.1 on 2025-05-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_last_accessed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mascot_name',
            field=models.CharField(blank=True, default='DefaultMascot', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default='Guest', max_length=20),
        ),
        migrations.AlterModelTable(
            name='theme',
            table='users_theme',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='users_userprofile',
        ),
    ]
