# Generated by Django 5.2.1 on 2025-05-30 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_mascot_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': '테마', 'verbose_name_plural': '테마 목록'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '사용자 프로필', 'verbose_name_plural': '사용자 프로필 목록'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='login_count',
            field=models.IntegerField(default=0, verbose_name='로그인 횟수'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=0, verbose_name='포인트'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points_used',
            field=models.IntegerField(default=0, verbose_name='사용한 포인트'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='bg_color',
            field=models.CharField(blank=True, max_length=15, verbose_name='배경 색상'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='테마 설명'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='display_name',
            field=models.CharField(max_length=30, verbose_name='표시 이름'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화 여부'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='main_color',
            field=models.CharField(blank=True, max_length=15, verbose_name='주요 색상'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='mascot_image',
            field=models.URLField(blank=True, verbose_name='마스코트 이미지 URL'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='테마 이름'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='preview_image',
            field=models.URLField(blank=True, verbose_name='미리보기 이미지 URL'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막 접속'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mascot_name',
            field=models.CharField(blank=True, default='DefaultMascot', max_length=20, verbose_name='마스코트 이름'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default='Guest', max_length=20, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='selected_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.theme', verbose_name='선택된 테마'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
