# Generated by Django 5.2.1 on 2025-05-31 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_theme_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='마스코트 이름')),
                ('image', models.ImageField(upload_to='mascots/gallery/', verbose_name='마스코트 이미지')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
            ],
            options={
                'verbose_name': '갤러리 마스코트',
                'verbose_name_plural': '갤러리 마스코트 목록',
                'db_table': 'users_mascot',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mascot_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='마스코트 애칭'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='selected_mascot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.mascot', verbose_name='선택 마스코트'),
        ),
    ]
