# Generated by Django 5.2.1 on 2025-05-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_mascot_alter_userprofile_mascot_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='mascot_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme_mascots/', verbose_name='마스코트 이미지'),
        ),
    ]
