# Generated by Django 5.2.1 on 2025-05-31 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_theme_mascot_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('allowance_request', '용돈 신청'), ('trophy_award', '트로피 획득'), ('shop_purchase', '상점 구매'), ('minigame_fee', '미니게임 참가비'), ('minigame_reward', '미니게임 보상'), ('admin_adjustment', '관리자 조정')], max_length=50, verbose_name='거래 유형')),
                ('points_changed', models.IntegerField(verbose_name='포인트 변경량')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='설명')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='거래 시각')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '포인트 거래 내역',
                'verbose_name_plural': '포인트 거래 내역 목록',
                'db_table': 'users_pointtransaction',
                'ordering': ['-timestamp'],
            },
        ),
    ]
