# Generated by Django 5.2.1 on 2025-06-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_pointtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='minigame_loss_count',
            field=models.IntegerField(default=0, verbose_name='미니게임 패배 수'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='minigame_win_count',
            field=models.IntegerField(default=0, verbose_name='미니게임 승리 수'),
        ),
    ]
