# Generated by Django 5.2.1 on 2025-06-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofile_minigame_loss_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='number_shooter_best',
            field=models.IntegerField(default=0, verbose_name='넘버슈터 최고점'),
        ),
    ]
