# Generated by Django 5.2.1 on 2025-06-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allowancerequest',
            table='shop_allowancerequest',
        ),
        migrations.AlterModelTable(
            name='item',
            table='shop_item',
        ),
        migrations.AlterModelTable(
            name='purchase',
            table='shop_purchase',
        ),
    ]
