# Generated by Django 5.2.1 on 2025-05-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_point',
            field=models.IntegerField(default=0),
        ),
    ]
