# Generated by Django 5.2.1 on 2025-05-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_total_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trophy',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='trophy',
            name='sound_url',
        ),
        migrations.AlterField(
            model_name='trophy',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='goal_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='point',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='trophy_type',
            field=models.CharField(choices=[('activity', '활동량'), ('correct', '정답수'), ('wrong', '오답정정')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='usertrophy',
            unique_together={('user', 'trophy')},
        ),
    ]
