# Generated by Django 5.2.1 on 2025-05-29 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100)),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('concept', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('concept', '개념문제'), ('past', '기출문제')], max_length=10)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('number', models.CharField(blank=True, max_length=10)),
                ('text', models.TextField()),
                ('image', models.URLField(blank=True)),
                ('choice1_text', models.CharField(max_length=200)),
                ('choice1_image', models.URLField(blank=True)),
                ('choice2_text', models.CharField(max_length=200)),
                ('choice2_image', models.URLField(blank=True)),
                ('choice3_text', models.CharField(max_length=200)),
                ('choice3_image', models.URLField(blank=True)),
                ('choice4_text', models.CharField(max_length=200)),
                ('choice4_image', models.URLField(blank=True)),
                ('answer', models.IntegerField()),
                ('explanation', models.TextField(blank=True)),
                ('explanation_image', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.lesson')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.subject')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.subject'),
        ),
    ]
