# Generated by Django 5.2.1 on 2025-05-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_useranswerlog_wronganswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice1_image',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice2_image',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice3_image',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice4_image',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation_image',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
