# Generated by Django 5.2.1 on 2025-05-30 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_question_choice1_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': '단원', 'verbose_name_plural': '단원 목록'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '문제', 'verbose_name_plural': '문제 목록'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': '과목', 'verbose_name_plural': '과목 목록'},
        ),
        migrations.AlterModelOptions(
            name='useranswerlog',
            options={'verbose_name': '사용자 답변 로그', 'verbose_name_plural': '사용자 답변 로그 목록'},
        ),
        migrations.AlterModelOptions(
            name='wronganswer',
            options={'verbose_name': '오답 기록', 'verbose_name_plural': '오답 기록 목록'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='concept',
            field=models.TextField(blank=True, verbose_name='개념 설명'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='grade',
            field=models.CharField(blank=True, max_length=10, verbose_name='학년'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='quiz.subject', verbose_name='과목'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='unit_name',
            field=models.CharField(max_length=100, verbose_name='단원 이름'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.IntegerField(verbose_name='정답 번호'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice1_image',
            field=models.URLField(blank=True, default='', null=True, verbose_name='선택지 1 이미지 URL'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice1_text',
            field=models.CharField(max_length=200, verbose_name='선택지 1 텍스트'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice2_image',
            field=models.URLField(blank=True, default='', null=True, verbose_name='선택지 2 이미지 URL'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice2_text',
            field=models.CharField(max_length=200, verbose_name='선택지 2 텍스트'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice3_image',
            field=models.URLField(blank=True, default='', null=True, verbose_name='선택지 3 이미지 URL'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice3_text',
            field=models.CharField(max_length=200, verbose_name='선택지 3 텍스트'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice4_image',
            field=models.URLField(blank=True, default='', null=True, verbose_name='선택지 4 이미지 URL'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice4_text',
            field=models.CharField(max_length=200, verbose_name='선택지 4 텍스트'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default='', null=True, verbose_name='해설'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation_image',
            field=models.URLField(blank=True, default='', null=True, verbose_name='해설 이미지 URL'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.URLField(blank=True, default='', null=True, verbose_name='문제 이미지 URL'),
        ),
        migrations.AlterField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='quiz.lesson', verbose_name='단원'),
        ),
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.CharField(blank=True, max_length=10, verbose_name='문제 번호'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('concept', '개념문제'), ('past', '기출문제')], max_length=10, verbose_name='문제 유형'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.subject', verbose_name='과목'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='문제 본문'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='question',
            name='year',
            field=models.CharField(blank=True, max_length=10, verbose_name='기출 연도'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=50, verbose_name='과목 이름'),
        ),
        migrations.AlterField(
            model_name='useranswerlog',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='정답 여부'),
        ),
        migrations.AlterField(
            model_name='useranswerlog',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_logs', to='quiz.question', verbose_name='문제'),
        ),
        migrations.AlterField(
            model_name='useranswerlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='제출 시간'),
        ),
        migrations.AlterField(
            model_name='useranswerlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_logs', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AlterField(
            model_name='useranswerlog',
            name='user_answer',
            field=models.IntegerField(verbose_name='선택한 답 번호'),
        ),
        migrations.AlterField(
            model_name='wronganswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록 시간'),
        ),
        migrations.AlterField(
            model_name='wronganswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_answers', to='quiz.question', verbose_name='문제'),
        ),
        migrations.AlterField(
            model_name='wronganswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_answers', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AlterUniqueTogether(
            name='useranswerlog',
            unique_together={('user', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='wronganswer',
            unique_together={('user', 'question')},
        ),
        migrations.AlterModelTable(
            name='lesson',
            table='quiz_lesson',
        ),
        migrations.AlterModelTable(
            name='question',
            table='quiz_question',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='quiz_subject',
        ),
        migrations.AlterModelTable(
            name='useranswerlog',
            table='quiz_useranswerlog',
        ),
        migrations.AlterModelTable(
            name='wronganswer',
            table='quiz_wronganswer',
        ),
    ]
