# Generated by Django 5.2.1 on 2025-06-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_lesson_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useranswerlog',
            unique_together=set(),
        ),
    ]
