"""Remove Theme model and user.selected_theme_id column

Revision ID: 6864e29ea705
Revises: 
Create Date: 2025-05-25 21:20:05.239138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6864e29ea705'
down_revision = None # 첫 번째 마이그레이션이므로 None이 맞습니다.
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - (부분적으로 조정됨) ###

    # 1. Theme 관련 삭제 작업 (순서 중요)
    op.drop_constraint('user_selected_theme_id_fkey', 'user', type_='foreignkey') 
    op.drop_column('user', 'selected_theme_id')
    op.drop_table('theme')

    # 2. PromptTemplate 'prompt_text' -> 'content' 컬럼 변경 (데이터 보존)
    #    2.1. 새 'content' 컬럼을 우선 nullable=True로 추가
    op.add_column('prompt_template', sa.Column('content', sa.TEXT(), nullable=True))
    
    #    2.2. 기존 'prompt_text' 컬럼의 데이터를 새 'content' 컬럼으로 복사
    #         (만약 prompt_text에 NULL이 있을 수 있다면, 그에 대한 처리도 고려해야 하지만, 여기서는 모든 값을 복사한다고 가정)
    op.execute('UPDATE prompt_template SET content = prompt_text')
    
    #    2.3. 'content' 컬럼을 nullable=False (NOT NULL)로 변경
    #         이때, 만약 위 UPDATE 이후에도 content 컬럼에 NULL이 남아있는 행이 있다면 오류가 발생합니다.
    #         모든 prompt_text가 값이 있었다고 가정하거나, 또는
    #         op.execute("UPDATE prompt_template SET content = '' WHERE content IS NULL") 등으로 기본값을 채워줘야 합니다.
    #         여기서는 prompt_text에 항상 값이 있었다고 가정합니다.
    op.alter_column('prompt_template', 'content',
                   existing_type=sa.TEXT(),
                   nullable=False)
                   
    #    2.4. 기존 'prompt_text' 컬럼 삭제
    op.drop_column('prompt_template', 'prompt_text')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - (부분적으로 조정됨) ###
    
    # PromptTemplate 컬럼 복원 (데이터는 content에서 prompt_text로 복사되지 않음 - 단순 스키마 복원)
    # 데이터까지 복원하려면 upgrade와 유사한 단계별 처리가 필요합니다.
    op.add_column('prompt_template', sa.Column('prompt_text', sa.TEXT(), nullable=True)) # nullable=True로 추가
    op.execute('UPDATE prompt_template SET prompt_text = content') # 데이터 복사
    op.alter_column('prompt_template', 'prompt_text', 
                    existing_type=sa.TEXT(), 
                    nullable=False) # NOT NULL로 변경
    op.drop_column('prompt_template', 'content')

    # Theme 관련 복원
    op.create_table('theme',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column('css_class', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='theme_pkey'), # op.f 제거
        sa.UniqueConstraint('css_class', name='theme_css_class_key'), # op.f 제거
        sa.UniqueConstraint('name', name='theme_name_key') # op.f 제거
    )
    op.add_column('user', sa.Column('selected_theme_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_selected_theme_id_fkey', 'user', 'theme', ['selected_theme_id'], ['id']) # op.f 제거
    
    # ### end Alembic commands ###