# Generated by Django 5.2.1 on 2025-05-29 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_theme_remove_userprofile_join_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='아이템명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('icon', models.URLField(blank=True, verbose_name='아이콘')),
                ('price', models.PositiveIntegerField(verbose_name='포인트 가격')),
                ('is_active', models.BooleanField(default=True, verbose_name='판매중')),
            ],
        ),
        migrations.CreateModel(
            name='AllowanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField(verbose_name='신청 포인트')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='신청일')),
                ('is_approved', models.BooleanField(default=False, verbose_name='승인여부')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='신청자')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='구매일시')),
                ('used', models.BooleanField(default=False, verbose_name='사용여부')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item', verbose_name='아이템')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='구매자')),
            ],
        ),
    ]
