# Generated by Django 5.2.1 on 2025-05-29 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.URLField(blank=True)),
                ('grade', models.CharField(default='bronze', max_length=20)),
                ('required_login_days', models.IntegerField(default=0, verbose_name='필요 출석일')),
                ('required_total_quiz', models.IntegerField(default=0, verbose_name='총 문제풀이')),
                ('required_subject', models.CharField(blank=True, max_length=20, verbose_name='특정 과목명')),
                ('required_subject_quiz', models.IntegerField(default=0, verbose_name='특정과목 문제풀이')),
                ('required_right_rate', models.IntegerField(default=0, verbose_name='정답률')),
                ('required_total_wrong', models.IntegerField(default=0, verbose_name='오답풀이')),
                ('required_streak', models.IntegerField(default=0, verbose_name='연속출석일')),
                ('required_point_used', models.IntegerField(default=0, verbose_name='포인트 사용량')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='트로피 포인트')),
            ],
        ),
        migrations.CreateModel(
            name='UserTrophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True, verbose_name='획득일시')),
                ('is_used', models.BooleanField(default=False, verbose_name='포인트 사용 여부')),
                ('trophy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trophies.trophy', verbose_name='트로피')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='유저')),
            ],
            options={
                'unique_together': {('user', 'trophy')},
            },
        ),
    ]
