# Generated by Django 5.2.1 on 2025-05-29 16:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trophies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertrophy',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='trophy',
            name='grade',
        ),
        migrations.AddField(
            model_name='usertrophy',
            name='achieved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertrophy',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='points',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='required_login_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='required_point_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='required_right_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='required_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='required_subject',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='required_subject_quiz',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='required_total_quiz',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='required_total_wrong',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usertrophy',
            name='trophy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trophies.trophy'),
        ),
        migrations.AlterField(
            model_name='usertrophy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='usertrophy',
            name='acquired_at',
        ),
        migrations.RemoveField(
            model_name='usertrophy',
            name='is_used',
        ),
    ]
