# Generated by Django 5.2.1 on 2025-05-30 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trophies', '0002_alter_usertrophy_unique_together_remove_trophy_grade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trophy',
            name='icon',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='required_subject',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='usertrophy',
            unique_together={('user', 'trophy')},
        ),
        migrations.AlterModelTable(
            name='trophy',
            table='trophies_trophy',
        ),
        migrations.AlterModelTable(
            name='usertrophy',
            table='trophies_usertrophy',
        ),
    ]
