# Generated by Django 5.2.1 on 2025-05-30 19:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trophies', '0003_alter_trophy_icon_alter_trophy_points_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trophy',
            options={'verbose_name': '트로피', 'verbose_name_plural': '트로피 목록'},
        ),
        migrations.AlterModelOptions(
            name='usertrophy',
            options={'verbose_name': '사용자 트로피', 'verbose_name_plural': '사용자 트로피 목록'},
        ),
        migrations.RemoveField(
            model_name='trophy',
            name='required_login_days',
        ),
        migrations.RemoveField(
            model_name='trophy',
            name='required_point_used',
        ),
        migrations.RemoveField(
            model_name='trophy',
            name='required_right_rate',
        ),
        migrations.RemoveField(
            model_name='trophy',
            name='required_streak',
        ),
        migrations.RemoveField(
            model_name='trophy',
            name='required_subject_quiz',
        ),
        migrations.RemoveField(
            model_name='trophy',
            name='required_total_quiz',
        ),
        migrations.RemoveField(
            model_name='trophy',
            name='required_total_wrong',
        ),
        migrations.RemoveField(
            model_name='usertrophy',
            name='achieved_at',
        ),
        migrations.AddField(
            model_name='trophy',
            name='condition_type',
            field=models.CharField(choices=[('login_days', '로그인 일수'), ('total_quiz', '총 문제풀이 수'), ('subject_quiz', '과목별 문제풀이 수'), ('right_rate', '정답률'), ('total_wrong', '총 오답 수'), ('streak', '연속 출석 일수'), ('point_used', '사용한 포인트')], default='login_days', max_length=50, verbose_name='조건 유형'),
        ),
        migrations.AddField(
            model_name='trophy',
            name='condition_value',
            field=models.IntegerField(default=0, verbose_name='조건 수치'),
        ),
        migrations.AddField(
            model_name='trophy',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일'),
        ),
        migrations.AddField(
            model_name='trophy',
            name='sound_effect',
            field=models.URLField(blank=True, default='', verbose_name='사운드 효과 URL'),
        ),
        migrations.AddField(
            model_name='trophy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AddField(
            model_name='usertrophy',
            name='awarded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='획득일'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trophy',
            name='description',
            field=models.TextField(verbose_name='트로피 설명'),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='icon',
            field=models.URLField(blank=True, default='', verbose_name='아이콘 URL'),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='트로피 이름'),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='points',
            field=models.IntegerField(default=0, verbose_name='획득 포인트'),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='required_subject',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='필요 과목'),
        ),
        migrations.AlterField(
            model_name='usertrophy',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='숨김 여부'),
        ),
        migrations.AlterField(
            model_name='usertrophy',
            name='trophy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trophies', to='trophies.trophy', verbose_name='트로피'),
        ),
        migrations.AlterField(
            model_name='usertrophy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trophies', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
