# Generated by Django 5.2.1 on 2025-06-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trophies', '0005_alter_trophy_options_alter_usertrophy_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trophy',
            name='condition_type',
            field=models.CharField(choices=[('login_days', '로그인 일수'), ('total_quiz', '총 문제풀이 수'), ('subject_quiz', '과목별 문제풀이 수'), ('right_rate', '정답률'), ('total_wrong', '총 오답 수'), ('streak', '연속 출석 일수'), ('point_used', '사용한 포인트'), ('game_win', '미니게임 승리'), ('game_loss', '미니게임 패배'), ('point_gained', '획득한 포인트'), ('trophy_count', '트로피 개수')], default='login_days', max_length=50, verbose_name='조건 유형'),
        ),
    ]
