# Generated by Django 5.2.1 on 2025-05-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancestreak',
            name='longest_streak',
            field=models.IntegerField(default=0),
        ),
    ]
