# Generated by Django 5.2.1 on 2025-06-04 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancestreak_longest_streak'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancestreak',
            options={'verbose_name': '연속 출석 기록', 'verbose_name_plural': '연속 출석 기록 목록'},
        ),
        migrations.AlterModelOptions(
            name='dailyattendance',
            options={'verbose_name': '일일 출석 기록', 'verbose_name_plural': '일일 출석 기록 목록'},
        ),
        migrations.AlterField(
            model_name='attendancestreak',
            name='last_date',
            field=models.DateField(verbose_name='마지막 출석일'),
        ),
        migrations.AlterField(
            model_name='attendancestreak',
            name='longest_streak',
            field=models.IntegerField(default=0, verbose_name='최장 연속 출석일'),
        ),
        migrations.AlterField(
            model_name='attendancestreak',
            name='streak_count',
            field=models.IntegerField(default=0, verbose_name='현재 연속 출석일'),
        ),
        migrations.AlterField(
            model_name='attendancestreak',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='checked_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='기록 시간'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='date',
            field=models.DateField(verbose_name='출석일'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyattendance',
            unique_together={('user', 'date')},
        ),
        migrations.AlterModelTable(
            name='attendancestreak',
            table='attendance_attendancestreak',
        ),
        migrations.AlterModelTable(
            name='dailyattendance',
            table='attendance_dailyattendance',
        ),
    ]
